spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-gw9thvsl.sql.tencentcdb.com:20204/db_api
    username: root
    password: 
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password: YTbaiduren
server:
  port: 8080
  servlet:
    context-path: /api

